version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow_password
      POSTGRES_DB: taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: development
    container_name: taskflow_api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow_password@postgres:5432/taskflow_db?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: